
server:
  port: 8080
  servlet:
    session:
      #Session超时时间设置为5小时，单位是秒，默认是30分钟
      timeout: 18000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sxxblog112?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: classpath:static/,file:static/

  thymeleaf:
    cache: false

  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: true
    settings:
      number_format: 0.##
      datetime_format: yyyy-MM-dd HH:mm:ss
      classic_compatible: true
    template-loader-path:
      - classpath:/templates

mybatis-plus:
  type-aliases-package: com.sxxblog112.entity
  configuration:
    call-setters-on-nulls: false
    #开启驼峰
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: uuid
      logic-not-delete-value: 1
      logic-delete-value: 0

logging:
  level:
    root: error #日志配置DEBUG,INFO,WARN,ERROR